/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * 
 * 
 * Ouais ouais je sais c'est un bordel, c'est a refaire mais tout va bien
 * 
 * 
 */
package projet.cpoo5;

import org.junit.jupiter.api.Test;
import projet.cpoo.wordGenerator.WordGenerator;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        WordGenerator classUnderTest = new WordGenerator("test");
        System.out.println("oui");
        assertTrue(classUnderTest.returnTrue(), "someLibraryMethod should return 'true'");
    }
}
